// img2logo converts a PNG image to colored terminal block art using the
// quadrant block character renderer (same pipeline as the game's Blocks mode).
//
// Usage:
//
//	go run ./cmd/img2logo <image.png> [width] [height]           # ANSI preview
//	go run ./cmd/img2logo --go <funcName> <image.png> [width] [height]  # Go source output
//
// width/height are in terminal character cells (default 20×10).
// The image is scaled to (width*2) × (height*4) pixels before rendering,
// which corrects for the typical 1:2 terminal cell aspect ratio.
package main

import (
	"fmt"
	"image"
	"image/color"
	"image/draw"
	_ "image/jpeg"
	_ "image/png"
	"os"
	"strconv"
	"strings"

	"github.com/charmbracelet/colorprofile"
	xdraw "golang.org/x/image/draw"

	"dev-null/internal/render"
)

func main() {
	args := os.Args[1:]

	// --go <funcName> mode: output Go source instead of ANSI preview.
	goMode := false
	funcName := ""
	if len(args) >= 2 && args[0] == "--go" {
		goMode = true
		funcName = args[1]
		args = args[2:]
	}

	if len(args) < 1 {
		fmt.Fprintf(os.Stderr, "usage: img2logo [--go funcName] <image.png> [width] [height]\n")
		os.Exit(1)
	}

	path := args[0]
	w, h := 20, 10
	if len(args) >= 2 {
		n, err := strconv.Atoi(args[1])
		if err != nil || n < 1 {
			fmt.Fprintf(os.Stderr, "invalid width %q\n", args[1])
			os.Exit(1)
		}
		w = n
	}
	if len(args) >= 3 {
		n, err := strconv.Atoi(args[2])
		if err != nil || n < 1 {
			fmt.Fprintf(os.Stderr, "invalid height %q\n", args[2])
			os.Exit(1)
		}
		h = n
	}

	buf := loadAndRender(path, w, h)

	if goMode {
		printGoSource(buf, funcName, w, h)
	} else {
		fmt.Println(buf.ToString(colorprofile.TrueColor))
	}
}

// loadAndRender loads a PNG, scales it, and returns the rendered ImageBuffer.
func loadAndRender(path string, w, h int) *render.ImageBuffer {
	f, err := os.Open(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "open: %v\n", err)
		os.Exit(1)
	}
	src, _, err := image.Decode(f)
	f.Close()
	if err != nil {
		fmt.Fprintf(os.Stderr, "decode: %v\n", err)
		os.Exit(1)
	}

	// Target pixel dimensions: w*2 wide, h*4 tall (aspect-ratio correction).
	pxW := w * 2
	pxH := h * 4

	// Fill with opaque black background (handles transparency).
	bg := image.NewRGBA(image.Rect(0, 0, pxW, pxH))
	for y := range pxH {
		for x := range pxW {
			bg.SetRGBA(x, y, color.RGBA{0, 0, 0, 255})
		}
	}

	// Scale source using Catmull-Rom for quality.
	scaled := image.NewRGBA(image.Rect(0, 0, pxW, pxH))
	xdraw.CatmullRom.Scale(scaled, scaled.Bounds(), src, src.Bounds(), xdraw.Over, nil)

	// Composite scaled image over the background.
	draw.Draw(bg, bg.Bounds(), scaled, image.Point{}, draw.Src)

	buf := render.NewImageBuffer(w, h)
	render.ImageToQuadrants(bg, buf, 0, 0, w, h)
	return buf
}

// printGoSource emits a Go function that reproduces the rendered buffer via
// buf.SetChar calls. Paste the output into a .go file in the target package.
func printGoSource(buf *render.ImageBuffer, funcName string, w, h int) {
	var sb strings.Builder

	sb.WriteString("// Code generated by cmd/img2logo. DO NOT EDIT.\n\n")
	sb.WriteString(fmt.Sprintf("// %s writes a %d×%d block-art logo into buf at offset (bx, by).\n", funcName, w, h))
	sb.WriteString(fmt.Sprintf("func %s(buf *render.ImageBuffer, bx, by int) {\n", funcName))

	for y := range h {
		for x := range w {
			px := buf.Pixels[y*w+x]
			fg := toRGBA(px.Fg)
			bg := toRGBA(px.Bg)
			sb.WriteString(fmt.Sprintf(
				"\tbuf.SetChar(bx+%d, by+%d, %q, color.RGBA{%d,%d,%d,255}, color.RGBA{%d,%d,%d,255}, render.AttrNone)\n",
				x, y, px.Char,
				fg.R, fg.G, fg.B,
				bg.R, bg.G, bg.B,
			))
		}
	}

	sb.WriteString("}\n")
	fmt.Print(sb.String())
}

func toRGBA(c color.Color) color.RGBA {
	if c == nil {
		return color.RGBA{0, 0, 0, 255}
	}
	r, g, b, a := c.RGBA()
	if a == 0 {
		return color.RGBA{0, 0, 0, 255}
	}
	return color.RGBA{uint8(r >> 8), uint8(g >> 8), uint8(b >> 8), 255}
}
